### ISSUE TITLE
Holiday / Special Days Reminders

### ISSUE THREAD

**Issue by SilvrrGIT** [SilvrrGIT/HomeAssistant#111]
@ccostan has a great implementation to remember holidays and special days.  

https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/config/packages/holiday.yaml

**Comment by CCOSTAN** [comment]
At least until 2020. :) I'll be watching to see if you update the JSON to 2030.. :) That should get us to the Rise of the AI revolution. :)

**Comment by SilvrrGIT** [comment]
I actually went to 2021 in my google calendar to get the non static dates and even google doesn't have those populated yet.

**Comment by CCOSTAN** [comment]
Check out https://www.calendarindex.com/holidays/2022/US
