### ISSUE TITLE
Avoid warning Template sensor lights_count has no entity ids configured to track 

### ISSUE THREAD

**Issue by gabrielemariotti** [SilvrrGIT/HomeAssistant#138]
Thanks for sharing your awesome configuration.

In your `HomeAssistant/sensors/template.yaml` you have some templates to count sensors. Using these templates without an `entity id` you should have this kind of warning in your ha logs:

`Template sensor lights_count has no entity ids configured to track nor were we able to extract the entities to track from the value template(s). This entity will only be able to be updated manually.`

Checking the [doc](https://www.home-assistant.io/components/sensor.template/#working-without-entities) you can use `entity_id: []` in your templates to avoid these messages.

Something like:

```
sensor_count:
        friendly_name: 'Number of Sensors'
        entity_id: []
        value_template: >
          {%- set domains = ['sensor'] -%}
          {%- for domain in domains -%}
            {%- for item in states[domain] -%}
              {% if loop.first %}
                {{loop.length}}
              {% endif %}
            {%- endfor -%}
          {%- endfor -%}


```

**Comment by SilvrrGIT** [comment]
@gabrielemariotti  Thanks so much!  This got rid of a lot of noise in my log!
