### ISSUE TITLE
I've used your midnight theme on my HA config. Thank you :)

### ISSUE THREAD

**Issue by UbhiTS** [SilvrrGIT/HomeAssistant#171]
Hi Adam. Your config has one of the most beautiful themes I've seen.
I've used and acknowledged it on my page.
Just wanted to say thanks 👍 

My config is here : https://github.com/UbhiTS/ha-config-ataraxis

**Comment by SilvrrGIT** [comment]
Glad you like it.  Be sure to read the breaking changes for 0.113.0, I think you caught the item around paper-card-background-color but it looks like they are going to be removing the use of anything with 'paper' in it in the near future.  I need to work on figuring out what some of the current 'paper' items control and replacing/removing them.

**Comment by UbhiTS** [comment]
I'll be honest, I'm not at all proficient in CSS. I'll just be following your updates on your repo and update mine from yours whenever you update your theme. I wish someday I become as good as you in styling, but that wish is far away at present :)

**Comment by SilvrrGIT** [comment]
I am not at all proficient at CSS either.  That theme is based off another theme called midnight that I found on the forum, then experimented with changes for along time and continued to tweak.  

I will be updating it though to get rid of all the 'paper' items per the breaking change.  Stay tuned.

**Comment by SilvrrGIT** [comment]
Ok, I updated and uploaded a change to the theme, it removes all the paper items that aren't in the default variables.  Everything on my UI still looks the same but I might not use all of the items available in the UI.  

Let me know if something isn't working for your UI and i can try and find a non-paper variable.

**Comment by UbhiTS** [comment]
That's awesome. I haven't updated my HA yet, will do it over the weekend and report back if I see any issues :)

**Comment by UbhiTS** [comment]
updated everything last night. everything looks good :) ... thanks for your work and support :)
I'll close this issue now. If I want to get in touch with you again, I'll open another issue :)
Thanks again !

**Comment by UbhiTS** [comment]
oops, spoke too soon, my thermostats page, as well as my room by room view of the house are not showing correctly.
1. thermostats > background is black, and also the colors are not right on the thermostat, they are showing as pink(ish) instead of yellow
2. room by room view > black background

If you can help whenever you have time, that would be awesome. And, how can I help, remote session ? share code via email ?

**Comment by SilvrrGIT** [comment]
1. I setup a thermostat card and I am not having any issues.  Double check that you don't have a theme specified for that card.  Also make sure that the view doesn't have a theme specified.  

2.  Again check that the view doesn't have a theme specified.  

If you can post an example of what you are seeing so I can understand better.  If you can post the YAML for your theme and the view.  pastebin works well for this kind of stuff.

**Comment by UbhiTS** [comment]
Oops, I'm sorry. my apologies, the issue was from my side. I have a chrome extension called Dark Reader, that was interfering with the rendering. The moment I disabled the extension, the thermostats page and the room by room view rendered absolutely fine :)
