### ISSUE TITLE
Secrets for Quick Links

### ISSUE THREAD

**Issue by Wrix79** [SilvrrGIT/HomeAssistant#172]
Hi SilvrrGIT

Could you please tell me the format of the secrets in the Quick links on the HA tab ie "!secret restart" etc

Thanks

Wrix

**Comment by SilvrrGIT** [comment]
Yup, the link just goes to the server controls page.  The restart secret is just the URL from the server control page copied out of the browser URL bar.

``` restart: https://homeassitanturl/config/server_control ```

I generally like to run a config check before I restart so I wanted a quick link to that page.  

You can also create a one click restart on the front end by creating an item that calls the ``` homeassistant.restart ``` service directly.
